[tool.poetry]
name = "zero-base-submit"
version = "0.1.0"
description = ""
authors = ["John Park <john.sw.park.00@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
